// Generated by `elixir bin/contracts.exs` from protocol/fixtures/subset.schema.json. Do not edit.
export type SubsetProbe = { readonly "__proto__"?: string; readonly "a/b~c"?: string; readonly "astral"?: string; readonly "big"?: number; readonly "counts"?: Readonly<Record<string, number>>; readonly "fixed"?: "x"; readonly "flag"?: boolean; readonly "n"?: number; readonly "nothing"?: null; readonly "tags"?: readonly (string)[] };

export type Contract = "SubsetProbe";

export const DEFS: Readonly<Record<Contract, unknown>> = {
  "SubsetProbe": JSON.parse("{\"additionalProperties\":false,\"examples\":[{\"big\":-9007199254740991,\"fixed\":\"x\",\"flag\":false,\"n\":-1,\"nothing\":null,\"tags\":[\"ab\"]},{\"big\":9007199254740991,\"n\":1},{},{\"astral\":\"𝒶\"},{\"a/b~c\":\"x\"},{\"counts\":{}},{\"counts\":{\"a\":0,\"bbb\":9007199254740991}}],\"properties\":{\"__proto__\":{\"type\":\"string\"},\"a/b~c\":{\"type\":\"string\"},\"astral\":{\"pattern\":\"^[^a]$\",\"type\":\"string\"},\"big\":{\"type\":\"integer\"},\"counts\":{\"additionalProperties\":{\"minimum\":0,\"type\":\"integer\"},\"maxProperties\":2,\"propertyNames\":{\"pattern\":\"^[a-z]{1,3}$\"},\"type\":\"object\"},\"fixed\":{\"const\":\"x\",\"type\":\"string\"},\"flag\":{\"type\":\"boolean\"},\"n\":{\"maximum\":1,\"minimum\":-1,\"type\":\"integer\"},\"nothing\":{\"type\":\"null\"},\"tags\":{\"items\":{\"minLength\":2,\"type\":\"string\"},\"type\":\"array\"}},\"type\":\"object\"}"),
};
