defmodule LokaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :loka

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # Session signing salt is configured per-environment:
  # - Dev/Test: Uses a fixed salt (safe for local development)
  # - Production: Requires SESSION_SIGNING_SALT env var (see runtime.exs)
  @session_options [
    store: :cookie,
    key: "_loka_key",
    signing_salt:
      Application.compile_env(:loka, :session_signing_salt, "dev_session_salt_do_not_use_in_prod"),
    same_site: "Lax",
    secure: true,
    http_only: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Mobile/native app socket with JWT authentication
  socket "/socket", LokaWeb.UserSocket,
    websocket: [check_origin: false],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :loka,
    gzip: not code_reloading?,
    only: LokaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Tidewave MCP server for AI coding assistance
  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # World Builder MCP server for Claude Desktop integration (dev only)
  # Forward before Plug.Parsers so the MCP router can handle its own JSON parsing
  if Application.compile_env(:loka, :dev_routes, false) do
    plug :world_builder_mcp_router

    defp world_builder_mcp_router(
           %Plug.Conn{path_info: ["world_builder_mcp" | rest]} = conn,
           _opts
         ) do
      conn
      |> Plug.forward(rest, Loka.WorldBuilder.MCP.Router, [])
      |> Plug.Conn.halt()
    end

    defp world_builder_mcp_router(conn, _opts), do: conn
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :loka
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS for mobile app development
  plug LokaWeb.Plugs.CORS

  plug LokaWeb.Router
end
