import Config

# Environment identifier for conditional logic
config :loka, :env, :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :loka, LokaWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled entirely by Fly.io's edge proxy:
# - fly.toml has force_https = true, which redirects HTTP->HTTPS at the edge
# - Internal health checks bypass the edge and hit the app directly on HTTP
# - We don't use Phoenix force_ssl because the exclude option doesn't work
#   reliably with Fly's internal health check requests
#
# Note: HSTS is not set by the app, but Fly.io's edge proxy handles this

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Log level - set LOG_LEVEL=debug for verbose output
# Defaults to :info in production

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
