import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :exmud, ExmudWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled by Fly.io's edge proxy, which terminates SSL and forwards
# plain HTTP to our app on port 8080. We enable force_ssl to:
# 1. Redirect any HTTP requests to HTTPS (via x_forwarded_proto header)
# 2. Set HSTS headers for browser security (max_age: 1 year)
# 3. Include subdomains in HSTS policy
config :exmud, ExmudWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    host: nil,
    expires: 31_536_000  # 1 year in seconds
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Log level - set LOG_LEVEL=debug for verbose output
# Defaults to :info in production

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
