import assert from 'node:assert/strict';
import { presenter } from './presenter.ts';
const view={place:{id:'landing',title:{key:'room.title'}},actions:[],entities:[],inventory:[],exits:[],journal:[],time:0};
let committed=false;
const game={view:()=>({view,token:'view:literal:0'}),pending:()=>false,text:()=>"You say you'll fetch it.",lastNarration:()=>{if(committed)throw new Error('controlled narration read fault');return undefined;},invoke:()=>{committed=true;return {kind:'saved',decision:{kind:'accepted',outcome:'chosen',narration:[{key:'quest.accepted'}]}};}};
const p=presenter(game as never);
assert.throws(()=>p.press({label:'Accept',action_key:'choose',target_ids:[],input:{}},'bram'),/controlled narration read fault/);
assert.equal(committed,true);
assert.deepEqual(p.screen().detail('bram'),[]);
assert.equal(p.screen().fault,undefined);
console.log('confirmed: saved choice followed by narration-read fault escapes press, leaves no result/fault feedback');
