import assert from 'node:assert/strict';
import { presenter } from './presenter.ts';
const item={ id:'lantern', kind:'item', name:'lantern.name', actions:[{action_key:'take', label:'action.take', available:true}] };
const view={ place:{id:'well',title:{key:'room.title'}}, actions:[], entities:[item], inventory:[], exits:[], journal:[], time:0 };
let pending=false;
const game={view:()=>({view,token:'view:literal:0'}),pending:()=>pending,lastNarration:()=>undefined,text:(key:string)=>key==='lantern.name'?'a brass lantern':undefined,invoke:()=>{pending=true;return {kind:'pending'};}};
const p=presenter(game as never);
p.press(p.screen().buttons.find(b=>b.action_key==='take')!);
assert.equal(p.screen().pending,true);
assert.equal(p.screen().returnWorld,false,'unconfirmed Take must retain item detail');
assert.deepEqual(p.screen().view.inventory,[]);
console.log('controlled pending Take retained detail without success');
