import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { openGame } from '../../authority/local-story/session.ts';
import { presenter } from './presenter.ts';
const fixture = JSON.parse(readFileSync(new URL('../../../protocol/fixtures/cartridge_sampler_hash.json', import.meta.url), 'utf8'));
const db = new DatabaseSync(':memory:');
const adapter = { execSync: (s:string)=>db.exec(s), isInTransactionSync:()=>db.isTransaction, runSync:(s:string,...p:any[])=>db.prepare(s).run(...p), getFirstSync:(s:string,...p:any[])=>db.prepare(s).get(...p)??null, getAllSync:(s:string,...p:any[])=>db.prepare(s).all(...p) };
const game = openGame(adapter as never, fixture, {newId: randomUUID, kernel_version:`loka-kernel@${'0'.repeat(40)}`});
const p = presenter(game);
const b = p.screen().buttons.find(b=>b.label==='Talk to Old Bram')!;
p.press(b,b.target_ids[0]);
console.log(JSON.stringify({live:p.screen().detail(b.target_ids[0]),last:game.lastNarration()?.lines,recovered:presenter(game).screen().detail(b.target_ids[0])}));
