import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

// Controlled authored cartridge only: a real lethal round must leave a reachable original dark-loft corpse.
test('controlled real browser dark-isle corpse recovery', async ({ app, screen }) => {
  const go = async (direction: string, room: string) => {
    await screen.getByRole('button', 'Map').tap();
    await screen.getByRole('button', `Go ${direction}`).tap();
    await expect(screen.getByRole('button', `Look, ${room}`)).toBeVisible();
    await expect(screen.getByText('save not confirmed')).not.toBeVisible();
  };
  const contents = () => screen.getByRole('button', /Contents, Character,/);
  await app.clearState();
  await screen.getByRole('button', 'Continue').tap();
  await expect(screen.getByRole('button', 'Look, Boathouse')).toBeVisible();
  await screen.getByRole('button', 'a small satchel, open').tap();
  await screen.getByRole('button', 'Take a small satchel').tap();
  await screen.getByRole('button', 'a torch, open').tap();
  await screen.getByRole('button', 'Take a torch').tap();
  await go('east', 'Ferry Landing');
  await go('south', 'Reed Path');
  await go('south', 'Reed Bank');
  await go('south', 'Mire Crossing');
  await go('east', 'Marsh Light');
  await screen.getByRole('button', 'Marsh glow').tap();
  await expect(screen.getByText('You follow the glow and find a wisp waiting above the reeds.')).toBeVisible();
  await screen.getByRole('button', 'Leave').tap();
  await go('west', 'Mire Crossing');
  await go('north', 'Reed Bank');
  await go('north', 'Reed Path');
  await go('north', 'Ferry Landing');
  await go('west', 'Boathouse');
  await contents().tap();
  await screen.getByRole('button', 'Equipment & Inventory').tap();
  await screen.getByRole('button', 'a torch, open').tap();
  await screen.getByRole('button', 'Ignite a torch').tap();
  await screen.getByRole('button', 'Put a torch in a small satchel').tap();
  await screen.getByRole('button', 'Leave').tap();
  await screen.getByRole('button', 'Rope ferry').tap();
  await screen.getByRole('button', 'Board — 2p').tap();
  await expect(screen.getByRole('button', 'Look, Fen Isle Landing')).toBeVisible();
  await go('east', 'Isle Hut');
  await go('up', 'Hut Loft');
  await screen.getByRole('button', 'a cellar rat, open').tap();
  await screen.getByRole('button', 'Attack a cellar rat').tap();
  await expect(screen.getByRole('button', 'Look, Chapel Nave')).toBeVisible();
  await app.restart();
  await screen.getByRole('button', 'Continue').tap();
  await expect(screen.getByRole('button', 'Look, Chapel Nave')).toBeVisible();
  await contents().tap();
  await screen.getByRole('button', 'Equipment & Inventory').tap();
  await expect(screen.getByRole('button', 'a small satchel, open')).not.toBeVisible();
  await expect(screen.getByRole('button', 'a torch, open')).not.toBeVisible();
  await screen.getByRole('button', 'Back to World').tap();
  await go('south', 'Chapel Steps');
  await go('south', 'North Gate');
  await go('south', 'Village Green');
  await go('south', 'Well Lane');
  await go('south', 'Ferry Landing');
  await go('west', 'Boathouse');
  await screen.getByRole('button', 'Rope ferry').tap();
  await expect(screen.getByText('Free passage to recover your belongings on the isle.')).toBeVisible();
  await app.screenshot('waived-original-corpse');
  await screen.getByRole('button', 'Board — free (corpse recovery)').tap();
  await expect(screen.getByRole('button', 'Look, Fen Isle Landing')).toBeVisible();
  await go('east', 'Isle Hut');
  await go('up', 'Hut Loft');
  await expect(screen.getByText('The loft is dark. You know the ladder leads down.')).toBeVisible();
  await app.screenshot('dark-loft-owned-corpse');
  await screen.getByRole('button', 'a fallen body, open').tap();
  await screen.getByRole('button', 'a small satchel, open').tap();
  await screen.getByRole('button', 'a torch, open').tap();
  await screen.getByRole('button', 'Take a torch').tap();
  await screen.getByRole('button', 'a fallen body, open').tap();
  await screen.getByRole('button', 'a small satchel, open').tap();
  await screen.getByRole('button', 'Take a small satchel').tap();
  await app.restart();
  await screen.getByRole('button', 'Continue').tap();
  await expect(screen.getByRole('button', 'Look, Hut Loft')).toBeVisible();
  await contents().tap();
  await screen.getByRole('button', 'Equipment & Inventory').tap();
  await expect(screen.getByRole('button', 'a torch, open')).toBeVisible();
  await expect(screen.getByRole('button', 'a small satchel, open')).toBeVisible();
  await expect(screen.getByRole('button', /Contents, Character,.*pennies 0 of 1000/)).toBeVisible();
  await app.screenshot('recovered-original-belongings-after-reload');
  await screen.getByRole('button', 'Back to World').tap();
  await go('down', 'Isle Hut');
  await go('west', 'Fen Isle Landing');
  await screen.getByRole('button', 'Rope ferry').tap();
  await screen.getByRole('button', 'Return — free').tap();
  await expect(screen.getByRole('button', 'Look, Boathouse')).toBeVisible();
  await screen.getByRole('button', 'Rope ferry').tap();
  await expect(screen.getByText('Fare: 2p.')).toBeVisible();
  await expect(screen.getByRole('button', 'Board — 2p')).not.toBeVisible();
  await app.screenshot('empty-corpse-no-waiver-or-fare');
});
